apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.configMap.namespace }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        - containerPort: {{ .Values.service.httpsPort }}
        volumeMounts:
        - name: nginx-claim0
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: tls-certs
          mountPath: /etc/nginx/certs
          readOnly: true
      volumes:
      - name: nginx-claim0
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      - name: nginx-config
        configMap:
          name: {{ .Values.configMap.name }}
      - name: tls-certs
        secret:
          secretName: {{ .Values.tlsSecretName }}