{{- if $.Values.persistanceEnabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
{{- end }}