apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ollama.fullname" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "ollama.fullname" . }}-service
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ollama.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ollama.selectorLabels" . | nindent 8 }}
    spec:
      runtimeClassName: {{ .Values.runtimeClassName }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
      - name: ollama
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 11434
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
            nvidia.com/gpu: {{ index .Values.resources.requests "nvidia.com/gpu" }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
            nvidia.com/gpu: {{ index .Values.resources.limits "nvidia.com/gpu" }}

        volumeMounts:
        - name: models-storage
          mountPath: /root/.ollama/models
      volumes:
      - name: models-storage
        persistentVolumeClaim:
          claimName: shared-models-storage
