apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-models-storage
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-client
