replicaCount: 4

image:
  repository: cbcrowe/pihole-unbound
  tag: latest

service:
  name: pihole-service
  type: LoadBalancer
  ports:
    - name: "53-tcp"
      port: 53
      targetPort: 53
    - name: "53-udp"
      port: 53
      protocol: UDP
      targetPort: 53
    - name: "67-udp"
      port: 67
      protocol: UDP
      targetPort: 67
    - name: "80-tcp"
      port: 80
      targetPort: 80
    - name: "443-tcp"
      port: 443
      targetPort: 443
    - name: "5335-tcp"
      port: 5335
      targetPort: 5335
  loadBalancerIP: x.x.x.x # Your LB IP

persistence:
  storageClassName: nfs-client
  size:
    claim0: 20Gi
    claim1: 100Mi