apiVersion: v1
kind: Service
metadata:
  name: homepage
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "3000"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    io.kompose.service: homepage