apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-uptime-kuma-service
spec:
  selector:
    app: {{ .Release.Name }}-uptime-kuma
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.service.port }}
  type: {{ .Values.service.type }}