apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-rw
  labels:
    app: pihole
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pihole
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - worker1
                    - worker2
                    - worker3
                    - worker4
                    - worker5
                    - clustermaster
      containers:
        - name: pihole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 53
              hostPort: 53
              protocol: TCP
            - containerPort: 53
              hostPort: 53
              protocol: UDP
            - containerPort: 67
              hostPort: 67
              protocol: UDP
            - containerPort: 80
              hostPort: 8001
              protocol: TCP
            - containerPort: 443
              hostPort: 4443
              protocol: TCP
            - containerPort: 5335
              hostPort: 5335
              protocol: TCP
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-claim0
            - mountPath: /etc/dnsmasq.d
              name: pihole-claim1
          env:
            - name: DNSMASQ_LISTENING
              value: "single"
            - name: DNSSEC
              value: '"true"'
            - name: FTLCONF_LOCAL_IPV4
              value: "x.x.x.x" # LoadBalancer IP
            - name: PIHOLE_DNS_
              value: "127.0.0.1#5335"
            - name: TZ
              value: "US/New_York"
            - name: WEBPASSWORD
              value: "your-password"
      hostname: clustermaster
      restartPolicy: Always
      volumes:
        - name: pihole-claim0
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.useExisting }}{{ .Values.persistence.existingClaimNames.claim0 }}{{ else }}pihole-claim0{{ end }}
        - name: pihole-claim1
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.useExisting }}{{ .Values.persistence.existingClaimNames.claim1 }}{{ else }}pihole-claim1{{ end }}