{{- if and .Values.persistence.enabled (not .Values.persistence.useExisting) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-claim0
  labels:
    io.kompose.service: pihole-claim0
spec:
  accessModes:
    - {{ index .Values.persistence.accessModes 0 }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.claim0 }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-claim1
  labels:
    io.kompose.service: pihole-claim1
spec:
  accessModes:
    - {{ index .Values.persistence.accessModes 0 }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.claim1 }}
{{- end }}